include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - camel_case_types
    - camel_case_extensions
    - library_names
    - library_private_types_in_public_api
    - type_init_formals
    - empty_constructor_bodies
    - unnecessary_getters_setters
    - unnecessary_this
    - prefer_expression_over_statement

analyzer:
  exclude: [build/]
